kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: MAN5pKUOd26l5k6XUU0gPI55scPDNYh0j1rhExEiy50EJA6yX7FyyUm/iNHrMt6gZGYVi39QVUSjCdwzqAcRYA==
      - identity: {}
